export const devices = [
  {
    deviceName: 'Mavic 3',
    deviceSerial: '29zusf67we0r28f6w',
    deviceFlightControllerSerial: '29zusf67we0r28f6w',
    deviceDescription: 'string',
    deviceCarePackInfo: 'string',
    deviceStatus: 'In Betrieb',
    deviceInstallation: new Date(2022, 8,15),
    deviceNextMaintenance: new Date(2023, 8,15),
    deviceAccessoires: [],
    deviceBatteries: [],
    deviceFirmware: '20.2.5'
  },
  {
    deviceName: 'Mini 3',
    deviceSerial: 'a89a6s8dbasd8923r',
    deviceFlightControllerSerial: 'a89a6s8dbasd8923r',
    deviceDescription: 'string',
    deviceCarePackInfo: 'string',
    deviceStatus: 'In Betrieb',
    deviceInstallation: new Date(2022, 8,15),
    deviceNextMaintenance: new Date(2023, 8,15),
    deviceAccessoires: [],
    deviceBatteries: [],
    deviceFirmware: '20.2.5'
  },
  {
    deviceName: 'Mavic 3',
    deviceSerial: '29zusf67345r28f6w',
    deviceFlightControllerSerial: '29zusf67345r28f6w',
    deviceDescription: 'string',
    deviceCarePackInfo: 'string',
    deviceStatus: 'In Betrieb',
    deviceInstallation: new Date(2022, 8,15),
    deviceNextMaintenance: new Date(2023, 8,15),
    deviceAccessoires: [],
    deviceBatteries: [],
    deviceFirmware: '20.2.5'
  },
  {
    deviceName: 'Mavic 3',
    deviceSerial: '29zde367we0r28f6w',
    deviceFlightControllerSerial: '29zde367we0r28f6w',
    deviceDescription: 'string',
    deviceCarePackInfo: 'string',
    deviceStatus: 'In Betrieb',
    deviceInstallation: new Date(2022, 8,15),
    deviceNextMaintenance: new Date(2023, 8,15),
    deviceAccessoires: [],
    deviceBatteries: [],
    deviceFirmware: '20.2.5'
  },
  {
    deviceName: 'Flarm',
    deviceSerial: 'a89a6s8dbasdr563r',
    deviceFlightControllerSerial: 'a89a6s8dbasdr563r',
    deviceDescription: 'string',
    deviceCarePackInfo: 'string',
    deviceStatus: 'In Betrieb',
    deviceInstallation: new Date(2022, 8,15),
    deviceNextMaintenance: new Date(2023, 8,15),
    deviceAccessoires: [],
    deviceBatteries: [],
    deviceFirmware: '20.2.5'
  },
  {
    deviceName: 'Matrice 350',
    deviceSerial: '29sa2f67we0r28f6w',
    deviceFlightControllerSerial: '29sa2f67we0r28f6w',
    deviceDescription: 'string',
    deviceCarePackInfo: 'string',
    deviceStatus: 'In Betrieb',
    deviceInstallation: new Date(2022, 8,15),
    deviceNextMaintenance: new Date(2023, 8,15),
    deviceAccessoires: [],
    deviceBatteries: [],
    deviceFirmware: '20.2.5'
  },
  {
    deviceName: 'Flarm',
    deviceSerial: 'ah866s8dbasd8923r',
    deviceFlightControllerSerial: 'ah866s8dbasd8923r',
    deviceDescription: 'string',
    deviceCarePackInfo: 'string',
    deviceStatus: 'In Betrieb',
    deviceInstallation: new Date(2022, 8,15),
    deviceNextMaintenance: new Date(2023, 8,15),
    deviceAccessoires: [],
    deviceBatteries: [],
    deviceFirmware: '20.2.5'
  },
  {
    deviceName: 'Aececore Noa',
    deviceSerial: '29zusf67we0r2o09w',
    deviceFlightControllerSerial: '29zusf67we0r2o09w',
    deviceDescription: 'string',
    deviceCarePackInfo: 'string',
    deviceStatus: 'In Betrieb',
    deviceInstallation: new Date(2022, 8, 15),
    deviceNextMaintenance: new Date(2023, 8, 15),
    deviceAccessoires: [],
    deviceBatteries: [],
    deviceFirmware: '20.2.5'
  }
]
